### ISSUE TITLE
Is there a place that we can send a pull request for `install-cli.sh` installation script?

### ISSUE THREAD

**Issue by PeterDaveHello** [depot/cli#122]
Can't find it in the repo, any chance can put it in the repo, so that pull requests can be made for it? Thanks!

**Comment by jacobwgillespie** [comment]
Hey, yep I've added it here: https://github.com/depot/cli/blob/main/install-cli.sh

We'll still have to sync it to the website repo on change, but it's a start!

**Comment by PeterDaveHello** [comment]
Sent a PR here https://github.com/depot/cli/pull/129, thanks!
