### ISSUE TITLE
[Question]: Configure Global project ID

### ISSUE THREAD

**Issue by rjshrjndrn** [depot/cli#268]
Is there any way to have global project id, say in the ~/.config/depot/depot.yaml, so that every git project doesn't have to have depot.json in .gitignore?

**Comment by lazylua** [comment]
Good to know that. But no, my projects doesn't have a common parent directory. But depot already have Api token stored in ~/. config/depot.yaml.cant we consider that as the global config file? And for project based config, per do rectory depot.json or yaml will take precedence?

**Comment by rjshrjndrn** [comment]
Good to know that. But no, my projects doesn't have a common parent directory. But depot already have Api token stored in ~/. config/depot.yaml.cant we consider that as the global config file? And for project based config, per do rectory depot.json or yaml will take precedence?
